name: Deploy dockerized Angular app

on:
    push:
        branches: ["main"]
jobs:
    # build-image:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Checkout repository
    #       uses: actions/checkout@v2
    #     # Login to Google Cloud
    #     - name: Login to Google Cloud
    #       uses: 'google-github-actions/auth@v2'
    #       with:
    #         credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    #      # Login to GCR
    #     - name: Login to Google Container Registry
    #       uses: docker/login-action@v3
    #       with:
    #         registry: gcr.io
    #         username: _json_key
    #         password: '${{ secrets.GOOGLE_CREDENTIALS }}'
    #     # Tag Docker image and push to Google Artifact Registry
    #     - name: Tag Docker image and push to Google
    #       uses: docker/build-push-action@v6
    #       with:
    #         push: true
    #         tags:  ${{secrets.CONTAINER_REGISTRY_ENDPOINT}}/angular-dockerized:latest
    deploy-app:
       # needs: build-image
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Setup SSH
          shell: bash
          run: |
            service ssh status
            eval `ssh-agent -s`
            mkdir -p /home/runner/.ssh/
            touch /home/runner/.ssh/id_rsa
            echo -e "${{secrets.SSH_PRIVATE_KEY}}" > /home/runner/.ssh/id_rsa
            chmod 700 /home/runner/.ssh/id_rsa
            ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{secrets.HOST}} >> /home/runner/.ssh/known_hosts
        - name: Run ansible script
          shell: bash
          run: |
           service ssh status
           ansible-playbook -i infrastructure/ansible/inventory.ini infrastructure/ansible/playbook.angular.yml -vvv -e "ansible_ssh_common_args='-o ConnectTimeout=30'"
          env:
            GCR_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_CREDENTIALS }}
